#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="bin,git,kitty,nvim,tmux,vim,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/code/jordanfjellman/dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
  stow --delete $folder
  stow --target=$HOME $folder
done
popd

ln -sf "$HOME/.vimrc" "$HOME/.ideavimrc"

