#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="aerospace,bin,colima,docker,fish,fjelly,ghostty,git,hammerspoon,mise,nvim,opencode,starship,tmux,vim,vscode,wezterm,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/code/personal/dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
  /opt/homebrew/bin/stow --delete $folder
  /opt/homebrew/bin/stow --target=$HOME $folder
done
popd

ln -sf "$HOME/.vimrc" "$HOME/.ideavimrc"

