require("fjellyvim.globals").setup()
require("fjellyvim.options").setup()
require("fjellyvim.plugins").setup()
require("fjellyvim.diagnostic").setup()
require("fjellyvim.diagnostic").setup_keymaps()
require("fjellyvim.theme").setup()
require("fjellyvim.lsp").setup_keymaps()
